name: Automated Versioning and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        run: npm run start

      - name: Run logger.js
        run: npm run logger

      - name: Get current package version
        id: package_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Increment version
        run: |
          npm version patch -m "Upgrade to version %s"

      - name: Commit and Push changes
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add .
          git diff --cached
          git commit -m "New Updates Detected & Webpack Update" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package_version.outputs.current_version }}
          release_name: Release v${{ steps.package_version.outputs.current_version }}
          body: |
            ## Changelog
            - Updated to version ${{ steps.package_version.outputs.current_version }}
